type teamFinanceTokens {
  id: ID!
  address: String!
  name: String!
  symbol: String!
  totalSupply: BigInt!
  owner: String!
  decimals: Int!
  txHash: String
  chainId: Int!
  timestamp: BigInt
  blockHeight: Int
  transactionIndex: Int
  ipfs: String
}

type deposits {
  id: ID! # Transaction hash
  blockHeight: Int
  depositId: BigInt! @index
  tokenAddress: String! @index
  withdrawalAddress: String!
  lockContractAddress: String!
  amount: BigInt!
  unlockTime: BigInt!
  chainId: Int!
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  token: token
  depositDetail: depositDetail
}

type depositNfts {
  id: ID! # Transaction hash
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  chainId: Int!
  lockContractAddress: String!
  depositId: BigInt!
  tokenAddress: String! @index
  tokenId: BigInt! @index
  withdrawalAddress: String!
  amount: BigInt!
  unlockTime: BigInt!
  nft: nft
  depositDetail: depositDetail
}

type lockDurationExtendeds {
  id: ID! # Transaction hash
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  chainId: Int!
  lockContractAddress: String!
  lockId: BigInt!
  unlockTime: BigInt!
}

type lockSplits {
  id: ID! # Transaction hash
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  chainId: Int!
  lockContractAddress: String!
  lockId: BigInt!
  remainingAmount: BigInt!
  splitLockId: BigInt!
  newSplitLockAmount: BigInt!
}

type logNftWithdrawals {
  id: ID! # Transaction hash
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  chainId: Int!
  lockContractAddress: String!
  lockId: BigInt!
  tokenAddress: String! @index
  tokenId: BigInt! @index
  withdrawalAddress: String!
  amount: BigInt!
  depositDetail: depositDetail
}

type logTokenWithdrawals {
  id: ID! # Transaction hash
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  chainId: Int!
  lockContractAddress: String!
  lockId: BigInt!
  tokenAddress: String! @index
  withdrawalAddress: String!
  amount: BigInt!
  depositDetail: depositDetail
}

type depositDetail {
  id: ID!
  chainId: Int!
  tokenAddress: String
  withdrawalAddress: String
  tokenAmount: BigInt
  unlockTime: BigInt
  withdrawn: Boolean
  tokenId: BigInt
  isNFT: Boolean
  migratedLockDepositId: BigInt
  isNFTMinted: Boolean
}

type token {
  id: ID!
  chainId: Int!
  name: String!
  symbol: String!
  address: String!
  totalSupply: BigInt!
  decimals: Int!
}

type nft {
  id: ID!
  chainId: Int!
  name: String!
  symbol: String!
  address: String!
  totalSupply: BigInt!
}

type vestingFactories {
  id: ID!
  chainId: Int!
  address: String!
  vestingsCreated: Int!
  feesAccrued: BigInt!
  uniV2Router: String!
  uniV2Pair: String!
  feesInUsd: BigInt!
  companyWallet: String!
}

type vestings {
  id: ID!
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  chainId: Int!
  creator: String!
  vestingAddress: String!
  token: String!
  merkleRoot: String!
  tokenTotal: BigInt!
  fee: BigInt!
  timestamp: BigInt!
  claimed: BigInt!
  tokenInfo: token
}

type vestingClaims {
  id: ID!
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  chainId: Int!
  account: String!
  vesting: String!
  amount: BigInt!
  timestamp: BigInt!
  userVesting: userVesting
  vestingDetail: vestings
}

type stakingPools {
  id: ID!
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  chainId: Int!
  stakingToken: String
  rewardToken: String
  startTime: BigInt
  endTime: BigInt
  precision: BigInt
  totalReward: BigInt
  stakingContract: String
  user: String
  stakingTokenInfo: token
  rewardTokenInfo: token
  poolIndex: BigInt
}

type stakingClaims {
  id: ID!
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  chainId: Int!
  user: String!
  amount: BigInt!
  poolIndex: BigInt!
  address: String!
}

type stakingDeposits {
  id: ID!
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  chainId: Int!
  user: String!
  amount: BigInt!
  poolIndex: BigInt!
  address: String!
}

type stakingWithdraws {
  id: ID!
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  chainId: Int!
  user: String!
  amount: BigInt!
  poolIndex: BigInt!
  address: String!
}

type multisendErc20s {
  id: ID!
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  chainId: Int!
  contractAddress: String
  tokenAddress: String
  recipients: [String!]
  amounts: [String!]
  token: token
  from: String
}

type multisendEths {
  id: ID!
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  chainId: Int!
  contractAddress: String
  recipients: [String!]
  amounts: [String!]
  from: String
}

type userPools {
  id: ID!
  chainId: Int!
  contractAddress: String
  poolIndex: BigInt
  user: String!
  deposit: BigInt
  withdraw: BigInt
  claimed: BigInt
}

type transferLocks {
  id: ID!
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  chainId: Int!
  contractAddress: String
  lockId: BigInt!
  receiverAddress: String!
}

type splitLocks {
  id: ID!
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  chainId: Int!
  contractAddress: String
  lockId: BigInt!
  splitAmount: BigInt!
  splitUnlockTime: BigInt!
  mintNFT: Boolean
}

type userVesting @entity {
  id: ID!
  chainId: Int!
  vestingContractAddress: String
  account: String!
  totalClaimed: BigInt!
}

type vestingRevokeds @entity {
  id: ID!
  blockHeight: Int
  txHash: String
  transactionIndex: Int
  timestamp: BigInt
  chainId: Int!
  account: String!
  vesting: String!
  amountUnvested: BigInt!
  userVesting: userVesting
  vestingDetail: vestings
}